<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WSPilotosWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/WSPilotosWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/WSPilotosWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://serverPiloto/">
    <import location="http://localhost:8080/ServiciosUber/WSPilotos?WSDL" namespace="http://serverPiloto/"/>
    <plnk:partnerLinkType name="WSPilotosLinkType">
        <plnk:role name="WSPilotosRole" portType="ns:WSPilotos"/>
    </plnk:partnerLinkType>
</definitions>
